#!/usr/bin/env python3
"""
Static site builder for the Bluesight Prototypes directory browser.

Walks the repository and generates an index.html in every directory containing
prototypes. Also writes a _search-index.json at the root so the global
search works without a server.

Usage:
    python3 build.py            # build into the current repo (in place)
    python3 build.py --root DIR # build into DIR

Configuration (constants below):
    TITLE            — sidebar/page title
    EXCLUDE_NAMES    — files/folders never included
    EXCLUDE_PREFIXES — name prefix patterns to skip (e.g. dotfiles)
    IFRAME_EXTS      — extensions that load in the iframe viewer
    DEFAULT_FILES    — auto-load these when entering a directory
"""

import argparse
import html
import json
import os
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path

# ---------- CONFIG ----------
TITLE = "Product Design Hub"

# Output directory. The build copies the source tree here, renames each user
# `index.html` to PROTOTYPE_FILENAME, and writes generated listings + the
# search index. The source tree is never modified.
OUTPUT_DIR = "_site"

# What name a user must give to a file they want auto-loaded inside the
# sidebar's iframe (e.g. `login-flow/landing.html`). Hidden from listings and
# search. A user `index.html` is treated separately: it serves as a bare
# landing page for the folder (no sidebar wrapping), and the build will not
# overwrite it.
LANDING_FILENAME = "landing.html"

# Marker written into every generated listing. Used to detect and clean up
# stale generated files that may have been committed by previous (in-place)
# builds, so they don't get treated as real prototypes after the copy.
BUILD_MARKER = "<!-- generated by build.py -->"

EXCLUDE_NAMES = {
    "index.html",            # generated listing or user bare-landing — never re-listed
    "_search-index.json",    # generated output
    "build.py",
    "deploy.yml",
    ".git",
    ".github",
    ".gitignore",
    ".gitattributes",
    ".gitmodules",
    "node_modules",
    "CNAME",
    ".nojekyll",
    "README.md",             # hidden from listings by convention (not rendered)
    "notes.md",              # rendered above the listing as sidebar content (case below)
    OUTPUT_DIR,              # never copy/list our own output dir
}
# Extra: anything starting with these is skipped too
EXCLUDE_PREFIXES = (".",)

# Names skipped during the source → _site copy. Narrower than EXCLUDE_NAMES:
# we DO copy `index.html` (real user bare-landings or stale generated listings
# — distinguished by the BUILD_MARKER), `landing.html` (user file passed
# through), and README files (rendered into listings). We DO NOT copy build
# artifacts, build.py itself, or _site. Dotfiles are skipped via
# EXCLUDE_PREFIXES, not this set.
COPY_SKIP_NAMES = {
    "_search-index.json",
    "build.py",
    "node_modules",
    "CNAME",
    OUTPUT_DIR,
}

IFRAME_EXTS = {
    "html", "htm", "pdf", "txt", "md", "log", "csv", "tsv", "json", "xml",
    "yaml", "yml", "js", "ts", "css", "py", "rb", "sh", "c", "cpp", "java",
    "go", "rs", "php", "sql",
    "jpg", "jpeg", "png", "gif", "webp", "svg", "bmp", "ico", "avif",
    "mp3", "wav", "ogg", "m4a", "aac", "flac",
    "mp4", "webm", "mov", "m4v",
}

# Files auto-loaded into the iframe when a folder is opened. Checked in order.
DEFAULT_FILES = [LANDING_FILENAME, "index.htm"]

DATE_FORMAT = "%Y-%m-%d %H:%M"
# ----------------------------


# ---------- File categorization ----------
CATEGORIES = {
    "image":   {"jpg", "jpeg", "png", "gif", "webp", "svg", "bmp", "ico", "heic", "tiff", "avif"},
    "video":   {"mp4", "mov", "avi", "mkv", "webm", "flv", "wmv", "m4v"},
    "audio":   {"mp3", "wav", "flac", "ogg", "m4a", "aac", "opus"},
    "archive": {"zip", "tar", "gz", "bz2", "7z", "rar", "xz", "tgz"},
    "code":    {"js", "ts", "jsx", "tsx", "py", "rb", "php", "go", "java", "c", "cpp", "h", "hpp",
                "rs", "sh", "bash", "html", "htm", "css", "scss", "sass", "less", "json",
                "yaml", "yml", "xml", "toml", "sql"},
    "doc":     {"pdf", "doc", "docx", "txt", "md", "rtf", "odt", "tex"},
    "sheet":   {"xls", "xlsx", "csv", "tsv", "ods"},
    "slides":  {"ppt", "pptx", "odp", "key"},
}


def file_category(ext: str, is_dir: bool) -> str:
    if is_dir:
        return "folder"
    for cat, exts in CATEGORIES.items():
        if ext in exts:
            return cat
    return "file"


def fmt_size(size: int) -> str:
    if size is None:
        return ""
    units = ["B", "KB", "MB", "GB", "TB"]
    i = 0
    n = float(size)
    while n >= 1024 and i < len(units) - 1:
        n /= 1024
        i += 1
    return f"{n:.0f} {units[i]}" if i == 0 else f"{n:.1f} {units[i]}"


def is_excluded(name: str) -> bool:
    """A name is excluded if it's in EXCLUDE_NAMES or starts with an excluded prefix."""
    if name in EXCLUDE_NAMES:
        return True
    for p in EXCLUDE_PREFIXES:
        if name.startswith(p):
            return True
    # Case-insensitive match for sidebar-related markdown (any case).
    # readme.md is hidden by convention; notes.md is hidden because it's
    # rendered into the sidebar instead.
    if name.lower() in ("readme.md", "notes.md"):
        return True
    return False


# ---------- Markdown renderer (mirrors the PHP version) ----------
def render_markdown(md: str, rel_base: str = "") -> str:
    md = md.replace("\r\n", "\n").replace("\r", "\n")

    # Extract fenced code blocks first
    code_blocks = []

    def stash_code(m):
        code_blocks.append(f"<pre><code>{html.escape(m.group(1))}</code></pre>")
        return f"\x00CB{len(code_blocks) - 1}\x00"

    md = re.sub(r"```[a-zA-Z0-9_-]*\n(.*?)\n```", stash_code, md, flags=re.DOTALL)

    out = []
    para = []
    list_type = None  # 'ul' | 'ol' | None

    def flush_para():
        if para:
            out.append(f"<p>{process_inline(' '.join(para), rel_base)}</p>")
            para.clear()

    def close_list():
        nonlocal list_type
        if list_type:
            out.append(f"</{list_type}>")
            list_type = None

    for line in md.split("\n"):
        t = line.strip()

        m = re.match(r"^\x00CB(\d+)\x00$", t)
        if m:
            flush_para(); close_list()
            out.append(code_blocks[int(m.group(1))])
            continue

        if t == "":
            flush_para(); close_list()
            continue

        m = re.match(r"^(#{1,6})\s+(.+?)\s*#*$", t)
        if m:
            flush_para(); close_list()
            lvl = len(m.group(1))
            out.append(f"<h{lvl}>{process_inline(m.group(2), rel_base)}</h{lvl}>")
            continue

        if re.match(r"^(-{3,}|\*{3,}|_{3,})$", t):
            flush_para(); close_list()
            out.append("<hr>")
            continue

        m = re.match(r"^>\s?(.*)$", t)
        if m:
            flush_para(); close_list()
            out.append(f"<blockquote>{process_inline(m.group(1), rel_base)}</blockquote>")
            continue

        m = re.match(r"^[-*+]\s+(.+)$", t)
        if m:
            flush_para()
            if list_type != "ul":
                close_list()
                out.append("<ul>")
                list_type = "ul"
            out.append(f"<li>{process_inline(m.group(1), rel_base)}</li>")
            continue

        m = re.match(r"^\d+\.\s+(.+)$", t)
        if m:
            flush_para()
            if list_type != "ol":
                close_list()
                out.append("<ol>")
                list_type = "ol"
            out.append(f"<li>{process_inline(m.group(1), rel_base)}</li>")
            continue

        close_list()
        para.append(t)

    flush_para(); close_list()
    return "".join(out)


def process_inline(text: str, rel_base: str) -> str:
    text = html.escape(text, quote=False)

    def resolve_url(url: str) -> str:
        check = url.strip().lower()
        if re.match(r"^(javascript|vbscript|data):", check):
            return "#"
        if re.match(r"^(https?://|mailto:|/|#)", url, flags=re.I):
            return url
        return url if rel_base == "" else f"{rel_base}/{url}"

    text = re.sub(r"`([^`]+)`", lambda m: f"<code>{m.group(1)}</code>", text)
    text = re.sub(
        r"!\[([^\]]*)\]\(([^)\s]+)\)",
        lambda m: f'<img src="{resolve_url(m.group(2))}" alt="{m.group(1)}">',
        text,
    )
    text = re.sub(
        r"\[([^\]]+)\]\(([^)\s]+)\)",
        lambda m: f'<a href="{resolve_url(m.group(2))}" target="_blank" rel="noopener">{m.group(1)}</a>',
        text,
    )
    text = re.sub(r"\*\*([^*\n]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<![A-Za-z0-9_])__([^_\n]+)__(?![A-Za-z0-9_])", r"<strong>\1</strong>", text)
    text = re.sub(r"\*([^*\n]+)\*", r"<em>\1</em>", text)
    text = re.sub(r"(?<![A-Za-z0-9_])_([^_\n]+)_(?![A-Za-z0-9_])", r"<em>\1</em>", text)
    return text


# ---------- HTML template ----------
HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__ — __DISPLAY_PATH__</title>
<meta name="robots" content="noindex, nofollow">
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,<svg%20xmlns=%22http://www.w3.org/2000/svg%22%20viewBox=%220%200%20188.59%20188.76%22><circle%20fill=%22%23004987%22%20cx=%2297.4%22%20cy=%2292.72%22%20r=%2239.78%22/><path%20fill=%22%2392d9ee%22%20d=%22M184.16,92.16c3.46,69.11-71,113.72-131.41,81.72C-8.55,141.29-12.74,54.34,46.32,17.16A87.26,87.26,0,0,1,96.44,4.45,101.22,101.22,0,0,0,71.38,9.57C1.76,34.69-7.75,128.7,57.43,165.16c56.69,29.91,122.83-9.84,126.73-73Z%22/><path%20fill=%22%233cb4e5%22%20d=%22M96.44,147.91c-31.2,2.53-58.75-24.71-58.29-55.75-.47-31,27.09-58.3,58.29-55.74-29.11,1.5-53.69,26.74-53.22,55.74-.48,29,24.1,54.27,53.22,55.75Z%22/><path%20fill=%22%2354c8e8%22%20d=%22M59.91,155.44C2.74,122.29,12.67,36.32,76.4,17.39c40.62-12.3,85.18,13.4,94.84,54.73,15.5,64.67-54.06,116.27-111.33,83.32Zm0,0c34,19.95,79.56,7,97.59-28,17.88-32.59,5.17-76.34-27.07-94.14-31.53-19-75.8-8.19-95.08,23.62C14,90.05,25.62,136,59.91,155.44Z%22/></svg>">
<style>
  :root {
    --bg: #fafafa;
    --surface: #ffffff;
    --surface-2: #f3f4f6;
    --border: #e5e7eb;
    --border-strong: #d1d5db;
    --text: #111827;
    --text-muted: #6b7280;
    --accent: #2563eb;
    --accent-soft: rgba(37, 99, 235, 0.1);
    --hover: #f3f4f6;

    --c-folder:  #eab308;
    --c-image:   #10b981;
    --c-video:   #8b5cf6;
    --c-audio:   #ec4899;
    --c-archive: #f97316;
    --c-code:    #3b82f6;
    --c-doc:     #ef4444;
    --c-sheet:   #16a34a;
    --c-slides:  #f59e0b;
    --c-file:    #9ca3af;

    --sidebar-w: 300px;
  }

  * { box-sizing: border-box; }
  html, body { height: 100%; margin: 0; }
  body {
    font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, Roboto, sans-serif;
    color: var(--text);
    background: var(--bg);
    color-scheme: light;
    -webkit-font-smoothing: antialiased;
    overflow: hidden;
  }

  .layout { position: relative; height: 100vh; }

  .sidebar {
    --surface: #021E35;
    --surface-2: #2a2a2a;
    --border: #044A82;
    --border-strong: #7097BB;
    --text: #e5e7eb;
    --text-muted: #9ca3af;
    --accent: #60a5fa;
    --accent-soft: rgba(96, 165, 250, 0.18);
    --hover: #0A3861;

    position: fixed;
    top: 0; left: 0; bottom: 0;
    width: var(--sidebar-w);
    background: var(--surface);
    color: var(--text);
    color-scheme: dark;
    border-right: 8px solid #7097BB;
    display: flex;
    flex-direction: column;
    z-index: 50;
    transition: transform 0.2s ease, box-shadow 0.2s ease, width 0.2s ease;
  }
  .sidebar header {
    padding: 14px 18px 10px;
  }
  .header-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 8px;
    margin-bottom: 6px;
  }
  .sidebar h1 {
    margin: 0;
    font-size: 16px;
    font-weight: 600;
    letter-spacing: -0.01em;
  }
  .icon-btn {
    background: none;
    border: none;
    color: var(--text-muted);
    cursor: pointer;
    padding: 4px;
    border-radius: 4px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }
  .icon-btn:hover { background: var(--hover); color: var(--text); }

  .crumbs {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    font-size: 12px;
    color: var(--text-muted);
    word-break: break-all;
    margin-bottom: 10px;
  }
  .crumbs a {
    color: var(--text-muted);
    text-decoration: none;
    padding: 1px 4px;
    border-radius: 4px;
  }
  .crumbs a:hover { color: var(--accent); background: var(--hover); }
  .crumbs .sep { margin: 0 1px; opacity: 0.6; }
  .crumbs a:last-child { color: var(--text); font-weight: 500; }

  .toolbar { display: flex; gap: 8px; align-items: center; }
  #search {
    flex: 1;
    min-width: 0;
    padding: 7px 10px 7px 30px;
    border: 1px solid var(--border-strong);
    border-radius: 6px;
    background: var(--surface) url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%239ca3af' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='11' cy='11' r='8'/><path d='m21 21-4.3-4.3'/></svg>") no-repeat 8px center;
    background-size: 14px;
    color: var(--text);
    font-size: 13px;
    outline: none;
  }
  #search:focus { border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-soft); }
  #search::placeholder { color: var(--text-muted); opacity: 0.7; }
  #sort {
    display: none;
    padding: 7px 8px;
    border: 1px solid var(--border-strong);
    border-radius: 6px;
    background: var(--surface);
    color: var(--text);
    font-size: 12px;
    cursor: pointer;
    outline: none;
  }
  #sort:focus { border-color: var(--accent); }

  .filelist {
    list-style: none;
    margin: 0;
    padding: 6px 0;
    overflow-y: auto;
    flex: 1;
  }
  .filelist li { margin: 0; }
  .row {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 7px 18px;
    text-decoration: none;
    color: var(--text);
    cursor: pointer;
    border-left: 2px solid transparent;
    min-width: 0;
  }
  .row:hover { background: var(--hover); }
  .row.active {
    background: var(--accent-soft);
    border-left-color: var(--accent);
  }
  .row .info { min-width: 0; flex: 1; }
  .row .name {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: 13.5px;
  }
  .row .meta {
    font-size: 11px;
    color: var(--text-muted);
    margin-top: 1px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-variant-numeric: tabular-nums;
  }
  #filelist .row .meta { display: none; }
  .icon { width: 18px; height: 18px; flex-shrink: 0; }
  .icon-folder  { color: var(--c-folder); }
  .icon-product { color: var(--text); }
  .icon-image   { color: var(--c-image); }
  .icon-video   { color: var(--c-video); }
  .icon-audio   { color: var(--c-audio); }
  .icon-archive { color: var(--c-archive); }
  .icon-code    { color: var(--c-code); }
  .icon-doc     { color: var(--c-doc); }
  .icon-sheet   { color: var(--c-sheet); }
  .icon-slides  { color: var(--c-slides); }
  .icon-file    { color: var(--c-file); }
  .icon-up      { color: var(--text-muted); }

  .empty-list {
    padding: 24px 18px;
    text-align: center;
    color: var(--text-muted);
    font-size: 13px;
  }

  .readme-row {
    list-style: none;
    padding: 0;
    margin: 0;
    border-top: 1px solid var(--border);
  }
  .readme {
    padding: 14px 18px;
    border-bottom: 1px solid var(--border);
    font-size: 13px;
    line-height: 1.55;
    color: var(--text);
    overflow-y: auto;
    max-height: 35vh;
    flex-shrink: 0;
  }
  .readme > *:first-child { margin-top: 0; }
  .readme > *:last-child { margin-bottom: 0; }
  .readme h1, .readme h2, .readme h3, .readme h4, .readme h5, .readme h6 {
    margin: 14px 0 6px;
    font-weight: 600;
    line-height: 1.3;
    letter-spacing: -0.01em;
  }
  .readme h1 { font-size: 16px; }
  .readme h2 { font-size: 14.5px; }
  .readme h3 { font-size: 13.5px; }
  .readme h4, .readme h5, .readme h6 { font-size: 13px; }
  .readme p { margin: 0 0 8px; }
  .readme a { color: var(--accent); text-decoration: none; }
  .readme a:hover { text-decoration: underline; }
  .readme ul, .readme ol { padding-left: 20px; margin: 0 0 8px; }
  .readme li { margin: 2px 0; }
  .readme code {
    background: rgba(255, 255, 255, 0.08);
    padding: 1px 5px;
    border-radius: 3px;
    font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
    font-size: 12px;
  }
  .readme pre {
    background: rgba(255, 255, 255, 0.06);
    padding: 8px 10px;
    border-radius: 4px;
    overflow-x: auto;
    margin: 8px 0;
  }
  .readme pre code { background: none; padding: 0; font-size: 12px; }
  .readme blockquote {
    border-left: 3px solid var(--border-strong);
    padding: 0 0 0 10px;
    margin: 8px 0;
    color: var(--text-muted);
  }
  .readme img { max-width: 100%; height: auto; border-radius: 4px; }
  .readme hr { border: none; border-top: 1px solid var(--border); margin: 12px 0; }

  .viewer {
    position: absolute;
    inset: 0;
    margin-left: var(--sidebar-w);
    background: var(--bg);
    transition: margin-left 0.2s ease;
  }
  .viewer-body { height: 100%; position: relative; background: var(--surface-2); }
  #frame { width: 100%; height: 100%; border: 0; background: var(--surface); display: block; }
  .viewer[data-active="false"] #frame { display: none; }

  /* Full-width sidebar when no file is loaded (the empty viewer is replaced
     by the sidebar itself filling the viewport). */
  .layout:has(.viewer[data-active="false"]) .sidebar { width: 100%; padding: 20vh 20vw; }
  .layout:has(.viewer[data-active="false"]) .viewer { display: none; }

  .bluesight-logo { display: none; width: 200px; height: auto; margin-bottom: 24px; }
  .layout:has(.viewer[data-active="false"]) .bluesight-logo { display: block; }

  .hover-zone { display: none; position: fixed; top: 0; left: 0; bottom: 0; width: 14px; z-index: 60; }

  .expand-btn { display: none !important; }

  .layout.collapsed .sidebar { transform: translateX(-100%); }
  .layout.collapsed .viewer { margin-left: 0; }
  .layout.collapsed .hover-zone { display: block; }
  .layout.collapsed .expand-btn { display: inline-flex; }
  .layout.collapsed .hover-zone:hover ~ .sidebar,
  .layout.collapsed .expand-btn:hover ~ .sidebar,
  .layout.collapsed .sidebar:hover {
    transform: translateX(0);
    box-shadow: 4px 0 16px rgba(0, 0, 0, 0.12);
  }
  .layout.collapsed .sidebar.peek-suppress {
    transform: translateX(-100%) !important;
    box-shadow: none !important;
  }
  .layout.locked-open #collapse-btn { display: none; }

  @media (max-width: 800px) {
    .sidebar { width: 100%; }
    .viewer { margin-left: 0; z-index: 70; }
    .viewer[data-active="false"] { display: none; }
    .hover-zone { display: none !important; }
    .layout:not(.collapsed) .expand-btn { display: none; }
  }
</style>
</head>
<body>
<div class="layout __INITIAL_LOCK__">
  <div class="hover-zone" aria-hidden="true"></div>
  <button class="expand-btn" id="expand-btn" title="Expand sidebar (z)" aria-label="Expand sidebar">
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg>
  </button>

  <aside class="sidebar">
    <header>
      <svg class="bluesight-logo" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"viewBox="0 0 374 79.6"><g><g><g><circle fill="#FFFFFF" cx="42.2" cy="39.2" r="15.7"/><path fill="#FFFFFF" d="M76.4,38.9c1.4,27.2-28,44.8-51.8,32.2C0.4,58.3-1.3,24,22,9.4c5.9-3.6,12.9-5.4,19.8-5c-3.3,0.3-6.7,0.9-9.9,2c-27.4,9.9-31.2,47-5.5,61.3C48.8,79.5,74.8,63.8,76.4,38.9L76.4,38.9z"/><path fill="#FFFFFF" d="M41.8,60.9c-12.3,1-23.2-9.7-23-22c-0.2-12.2,10.7-23,23-22c-11.5,0.6-21.2,10.5-21,22C20.6,50.4,30.3,60.3,41.8,60.9L41.8,60.9z"/><path fill="#FFFFFF" d="M27.4,63.9C4.8,50.8,8.8,16.9,33.9,9.5c16-4.8,33.6,5.3,37.4,21.6C77.4,56.5,50,76.9,27.4,63.9L27.4,63.9zM27.4,63.9c13.4,7.9,31.4,2.8,38.5-11c7.1-12.8,2-30.1-10.7-37.1C42.8,8.2,25.3,12.5,17.7,25C9.3,38.1,13.9,56.2,27.4,63.9L27.4,63.9z"/></g><g><g><g><path fill="#FFFFFF" d="M103.2,24.4c1.8,0,3.4,0.2,4.8,0.5c1.4,0.3,2.7,0.8,3.7,1.5c1,0.7,1.8,1.6,2.3,2.6c0.5,1.1,0.8,2.3,0.8,3.8c0,0.8-0.1,1.5-0.3,2.2c-0.2,0.7-0.5,1.3-0.9,1.9c-0.4,0.6-0.9,1-1.4,1.5c-0.5,0.4-1.1,0.7-1.8,1c0.7,0.2,1.4,0.6,2,1c0.6,0.4,1.2,0.9,1.6,1.5c0.5,0.6,0.8,1.2,1.1,2c0.3,0.7,0.4,1.5,0.4,2.3c0,1.5-0.3,2.7-0.8,3.8c-0.5,1.1-1.3,2-2.2,2.7c-1,0.7-2.2,1.3-3.6,1.6c-1.4,0.4-3.1,0.5-4.9,0.5H90.7V24.4H103.2z M96.8,29.7v7.1h6.2c0.8,0,1.5,0,2.1-0.1c0.7-0.1,1.2-0.3,1.7-0.5c0.5-0.3,0.9-0.6,1.1-1.1c0.3-0.5,0.4-1.1,0.4-1.8c0-0.7-0.1-1.3-0.4-1.8c-0.3-0.5-0.7-0.8-1.2-1.1c-0.5-0.3-1.1-0.4-1.7-0.5c-0.7-0.1-1.4-0.2-2.1-0.2H96.8z M96.8,42.2v7.3l6.8,0c0.8,0,1.6-0.1,2.3-0.2c0.7-0.1,1.2-0.3,1.7-0.6c0.5-0.3,0.8-0.7,1.1-1.1c0.3-0.5,0.4-1.1,0.4-1.8c0-0.7-0.1-1.3-0.4-1.8c-0.3-0.5-0.6-0.8-1.1-1.1c-0.5-0.3-1-0.5-1.7-0.6c-0.7-0.1-1.4-0.2-2.3-0.2H96.8z"/></g><g><polygon fill="#FFFFFF" points="144.2,54.9 122,54.9 122,24.4 128.1,24.4 128.1,49.2 144.2,49.2 					"/></g><g><path fill="#FFFFFF" d="M174.4,42.7c0,2.1-0.3,4-1,5.6c-0.6,1.6-1.5,2.9-2.7,4c-1.2,1.1-2.6,1.9-4.2,2.4c-1.6,0.5-3.4,0.8-5.3,0.8c-1.9,0-3.7-0.3-5.3-0.8c-1.6-0.5-3-1.3-4.2-2.4c-1.2-1.1-2.1-2.4-2.7-4c-0.6-1.6-1-3.4-1-5.6V24.4h6.1v18c0,1.2,0.2,2.3,0.5,3.2c0.3,0.9,0.8,1.7,1.4,2.2c0.6,0.6,1.4,1,2.2,1.3c0.9,0.3,1.8,0.4,2.9,0.4c1,0,2-0.1,2.9-0.4c0.9-0.3,1.6-0.7,2.2-1.3c0.6-0.6,1.1-1.3,1.4-2.2c0.3-0.9,0.5-2,0.5-3.2v-18h6.1V42.7z"/></g><g><polygon fill="#FFFFFF" points="204.9,54.9 182.1,54.9 182.1,24.4 204.7,24.4 204.7,30 188.2,30 188.2,36.7 204,36.7 204,42.3 188.2,42.3 188.2,49.3 204.9,49.3 					"/></g><g><path fill="#FFFFFF" d="M233.3,32.1c-1.2-0.7-2.5-1.4-4-1.9c-1.4-0.5-3-0.7-4.7-0.7c-0.9,0-1.6,0.1-2.4,0.3c-0.7,0.2-1.3,0.4-1.8,0.7c-0.5,0.3-0.9,0.7-1.2,1.1c-0.3,0.4-0.4,1-0.4,1.5c0,0.6,0.2,1,0.5,1.4c0.3,0.4,0.7,0.7,1.3,1c0.6,0.3,1.2,0.5,2,0.7c0.8,0.2,1.6,0.3,2.5,0.5l1.7,0.3c1.4,0.2,2.6,0.5,3.8,1c1.2,0.4,2.2,1,3.1,1.7c0.9,0.7,1.6,1.5,2.1,2.5c0.5,1,0.8,2.1,0.8,3.4c0,1.7-0.3,3.2-1,4.4c-0.7,1.2-1.6,2.3-2.8,3.1c-1.2,0.8-2.5,1.4-4,1.8c-1.5,0.4-3.1,0.6-4.7,0.6c-1.2,0-2.3-0.1-3.5-0.3c-1.2-0.2-2.3-0.4-3.4-0.8c-1.1-0.3-2.2-0.8-3.2-1.3c-1-0.5-1.9-1.1-2.7-1.7l3.2-4.9c0.6,0.4,1.2,0.9,1.9,1.3c0.7,0.4,1.5,0.8,2.3,1.1c0.8,0.3,1.7,0.5,2.6,0.7c0.9,0.2,1.9,0.3,2.9,0.3c0.8,0,1.6-0.1,2.4-0.2c0.7-0.2,1.4-0.4,1.9-0.7c0.5-0.3,1-0.7,1.3-1.2c0.3-0.4,0.5-1,0.5-1.6c0-0.5-0.1-1-0.4-1.4c-0.3-0.4-0.7-0.7-1.2-1c-0.5-0.3-1.2-0.5-2-0.7c-0.8-0.2-1.7-0.4-2.8-0.6l-1.9-0.3c-1.4-0.2-2.6-0.5-3.7-1c-1.1-0.4-2.1-1-2.9-1.7c-0.8-0.7-1.5-1.5-1.9-2.6c-0.5-1-0.7-2.2-0.7-3.6c0-1.6,0.3-3,1-4.2c0.7-1.2,1.5-2.2,2.7-3c1.1-0.8,2.4-1.4,3.9-1.8c1.5-0.4,3-0.6,4.6-0.6c1.1,0,2.1,0.1,3.1,0.2c1,0.1,2,0.3,2.9,0.6c0.9,0.3,1.9,0.6,2.8,1c0.9,0.4,1.9,0.9,2.8,1.5L233.3,32.1z"/></g><g><rect x="243.7" y="24.4" fill="#FFFFFF" width="6.1" height="30.5"/></g><g><path fill="#FFFFFF" d="M272.9,23.8c2.4,0,4.6,0.4,6.6,1.2c2,0.8,3.6,2,5,3.5l-4.4,4.3c-0.9-1-1.9-1.8-3.2-2.4c-1.2-0.6-2.6-0.9-4.2-0.9c-1.4,0-2.7,0.2-3.9,0.7c-1.2,0.5-2.2,1.2-3.1,2.1c-0.9,0.9-1.5,1.9-2,3.2c-0.5,1.2-0.7,2.6-0.7,4.1c0,1.6,0.2,3,0.7,4.2c0.5,1.2,1.2,2.3,2,3.2c0.9,0.9,1.9,1.6,3,2c1.2,0.5,2.4,0.7,3.7,0.7c2.5,0,4.5-0.6,5.9-1.7c1.4-1.2,2.4-2.8,2.8-5h-7.8V38h14c0,0.3,0.1,0.6,0.1,0.9c0,0.3,0,0.6,0,0.9c0,2.3-0.4,4.4-1.1,6.4c-0.7,1.9-1.8,3.6-3.1,5c-1.3,1.4-2.9,2.5-4.7,3.3c-1.8,0.8-3.8,1.2-6,1.2c-1.4,0-2.8-0.2-4.1-0.5c-1.3-0.3-2.6-0.8-3.8-1.4c-1.2-0.6-2.3-1.4-3.3-2.3c-1-0.9-1.8-2-2.5-3.1c-0.7-1.2-1.3-2.5-1.7-3.9c-0.4-1.4-0.6-2.9-0.6-4.6c0-2.3,0.4-4.4,1.2-6.4c0.8-1.9,1.9-3.6,3.3-5c1.4-1.4,3.1-2.5,5.1-3.3C268.4,24.2,270.5,23.8,272.9,23.8"/></g><g><polygon fill="#FFFFFF" points="300.5,36.7 315.2,36.7 315.2,24.4 321.3,24.4 321.3,54.9 315.2,54.9 315.2,42.3 300.5,42.3 300.5,54.9 294.4,54.9 294.4,24.4 300.5,24.4 					"/></g><g><polygon fill="#FFFFFF" points="351.8,30.1 342.3,30.1 342.3,54.9 336.2,54.9 336.2,30.1 326.8,30.1 326.8,24.4 351.8,24.4 					"/></g></g></g></g><path fill="#FFFFFF" d="M358.1,30.1v-4.5h-1.8v-1.2h5v1.2h-1.8v4.5H358.1z M367.7,30.1v-3.9l-1.3,3.4H365l-1.3-3.4v3.9h-1.3v-5.7h1.9l1.4,3.6l1.4-3.6h1.9v5.7H367.7z"/></g></svg>
      <div class="header-row">
        <h1>__TITLE__</h1>
        <button class="icon-btn" id="collapse-btn" title="Collapse sidebar (z)" aria-label="Collapse sidebar">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg>
        </button>
      </div>
      <nav class="crumbs">__CRUMBS__</nav>
      <div class="toolbar">
        <input id="search" type="search" placeholder="Search all files…" autocomplete="off">
        <select id="sort" title="Sort by">
          <option value="name">Name</option>
          <option value="size">Size</option>
          <option value="mtime">Modified</option>
        </select>
      </div>
    </header>

    <ul class="filelist" id="search-results" hidden></ul>
    <ul class="filelist" id="filelist">
      __PARENT_ROW__
      __README_BLOCK__
      __ENTRY_ROWS__
      __EMPTY_NOTE__
    </ul>
  </aside>

  <main class="viewer" data-active="__VIEWER_ACTIVE__">
    <div class="viewer-body">
      <iframe id="frame" src="__FRAME_SRC__" title="File preview"></iframe>
    </div>
  </main>
</div>

<script>
(function() {
  const layout      = document.querySelector('.layout');
  const sidebar     = document.querySelector('.sidebar');
  const filelist    = document.getElementById('filelist');
  const searchRes   = document.getElementById('search-results');
  const search      = document.getElementById('search');
  const sortSel     = document.getElementById('sort');
  const frame       = document.getElementById('frame');
  const viewer      = document.querySelector('.viewer');
  const collapseBtn = document.getElementById('collapse-btn');
  const expandBtn   = document.getElementById('expand-btn');

  const allItems = [...filelist.querySelectorAll('li')].filter(li => li.querySelector('.row:not(.parent)'));
  const allRows  = allItems.map(li => li.querySelector('.row'));

  // SEARCH_INDEX_PATH is the relative URL from THIS page to /_search-index.json.
  const SEARCH_INDEX_PATH = '__SEARCH_INDEX_PATH__';
  // SITE_BASE is the relative URL from THIS page to the site root.
  const SITE_BASE = '__SITE_BASE__';

  function isHtmlFile(name) { return /\.html?$/i.test(name); }

  function setActive(absHref, name) {
    if (absHref) {
      frame.src = absHref;
      viewer.dataset.active = 'true';
    } else {
      frame.src = 'about:blank';
      viewer.dataset.active = 'false';
    }
    allRows.forEach(r => r.classList.toggle('active', r.dataset.absHref === absHref));
  }

  function applyLockForFile(isHtml) {
    if (isHtml) {
      layout.classList.remove('locked-open');
    } else {
      layout.classList.add('locked-open');
      layout.classList.remove('collapsed');
    }
  }

  function setCollapsed(collapsed) {
    if (collapsed && layout.classList.contains('locked-open')) return;
    layout.classList.toggle('collapsed', collapsed);
  }

  // ---- File click ----
  filelist.addEventListener('click', (e) => {
    const link = e.target.closest('a.row');
    if (!link || !link.dataset.iframe) return;
    e.preventDefault();
    setActive(link.dataset.absHref, link.dataset.name);
    applyLockForFile(isHtmlFile(link.dataset.name));
    history.replaceState({}, '', '#' + encodeURIComponent(link.dataset.name));
  });

  // ---- Restore from hash on load ----
  function restoreFromHash() {
    const h = decodeURIComponent(location.hash.slice(1));
    if (!h) return;
    const match = allRows.find(r => r.dataset.name === h && r.dataset.iframe);
    if (match) {
      setActive(match.dataset.absHref, match.dataset.name);
      applyLockForFile(isHtmlFile(match.dataset.name));
    }
  }
  restoreFromHash();
  window.addEventListener('hashchange', restoreFromHash);

  // ---- Sidebar toggle ----
  collapseBtn.addEventListener('click', () => {
    setCollapsed(true);
    sidebar.classList.add('peek-suppress');
  });
  sidebar.addEventListener('mouseleave', () => sidebar.classList.remove('peek-suppress'));
  expandBtn.addEventListener('click', () => setCollapsed(false));

  // ---- Global search ----
  const ICON_PATHS = {
    folder:  '<path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/>',
    image:   '<rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/>',
    video:   '<path d="m22 8-6 4 6 4V8Z"/><rect width="14" height="12" x="2" y="6" rx="2" ry="2"/>',
    audio:   '<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',
    archive: '<rect width="20" height="5" x="2" y="3" rx="1"/><path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/>',
    code:    '<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>',
    doc:     '<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><line x1="10" y1="9" x2="8" y2="9"/>',
    sheet:   '<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/><path d="M8 13h8M8 17h8M8 9h2"/>',
    slides:  '<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/><rect x="8" y="12" width="8" height="6" rx="1"/>',
    file:    '<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/>',
  };
  const iconHtml = (cat) => `<svg class="icon icon-${cat}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${ICON_PATHS[cat] || ICON_PATHS.file}</svg>`;
  const escapeHtml = (s) => s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  let treeCache = null, treePromise = null, lastQuery = '';
  const RESULT_LIMIT = 200;

  function fetchTree() {
    if (treeCache) return Promise.resolve(treeCache);
    if (treePromise) return treePromise;
    treePromise = fetch(SEARCH_INDEX_PATH)
      .then(r => r.json())
      .then(d => { treeCache = d; return d; })
      .catch(() => { treeCache = []; return []; })
      .finally(() => { treePromise = null; });
    return treePromise;
  }

  function showLocalList() { searchRes.hidden = true; filelist.hidden = false; }
  function showSearchResults() { filelist.hidden = true; searchRes.hidden = false; }

  function rankItem(item, q) {
    const n = item.name.toLowerCase();
    if (n === q) return 0;
    if (n.startsWith(q)) return 1;
    if (n.includes(q)) return 2;
    return 3;
  }

  function renderResults(q) {
    if (!treeCache) {
      searchRes.innerHTML = '<li class="empty-list">Loading file index…</li>';
      showSearchResults();
      return;
    }
    const matches = [];
    for (const item of treeCache) {
      const n = item.name.toLowerCase(), p = item.path.toLowerCase();
      if (n.includes(q) || p.includes(q)) matches.push({ item, score: rankItem(item, q) });
    }
    matches.sort((a, b) => {
      if (a.score !== b.score) return a.score - b.score;
      if (a.item.isDir !== b.item.isDir) return a.item.isDir ? -1 : 1;
      return a.item.name.localeCompare(b.item.name, undefined, { numeric: true, sensitivity: 'base' });
    });
    if (matches.length === 0) {
      searchRes.innerHTML = '<li class="empty-list">No matches.</li>';
      showSearchResults();
      return;
    }
    const visible = matches.slice(0, RESULT_LIMIT);
    const html = visible.map(({ item }) => {
      // Build URL relative to current page using SITE_BASE.
      let href;
      if (item.isDir) {
        href = SITE_BASE + item.path + '/';
      } else if (item.parent) {
        href = SITE_BASE + item.parent + '/#' + encodeURIComponent(item.name);
      } else {
        href = SITE_BASE + '#' + encodeURIComponent(item.name);
      }
      const where = item.parent ? '/' + escapeHtml(item.parent) : '/';
      return `<li><a class="row" href="${href}">${iconHtml(item.cat)}<div class="info"><div class="name">${escapeHtml(item.name)}</div><div class="meta">${where}</div></div></a></li>`;
    }).join('');
    let footer = '';
    if (matches.length > RESULT_LIMIT) {
      const extra = matches.length - RESULT_LIMIT;
      footer = `<li class="empty-list">${extra} more match${extra === 1 ? '' : 'es'} — refine your search</li>`;
    }
    searchRes.innerHTML = html + footer;
    showSearchResults();
  }

  search.addEventListener('input', () => {
    const q = search.value.trim().toLowerCase();
    lastQuery = q;
    if (!q) { showLocalList(); return; }
    if (treeCache) {
      renderResults(q);
    } else {
      searchRes.innerHTML = '<li class="empty-list">Loading file index…</li>';
      showSearchResults();
      fetchTree().then(() => { if (lastQuery) renderResults(lastQuery); });
    }
  });

  document.addEventListener('keydown', (e) => {
    const tag = (document.activeElement?.tagName || '').toLowerCase();
    const isTyping = tag === 'input' || tag === 'textarea' || tag === 'select';
    if (e.key === '/' && !isTyping) { e.preventDefault(); search.focus(); search.select(); }
    else if ((e.key === 'z' || e.key === 'Z') && !isTyping && !e.metaKey && !e.ctrlKey && !e.altKey) {
      e.preventDefault();
      const willCollapse = !layout.classList.contains('collapsed');
      setCollapsed(willCollapse);
      if (willCollapse) sidebar.classList.add('peek-suppress');
    } else if (e.key === 'Escape' && layout.classList.contains('collapsed')) {
      setCollapsed(false);
    }
  });

  // ---- Sort ----
  sortSel.addEventListener('change', () => {
    const key = sortSel.value;
    const sorted = allItems.slice().sort((a, b) => {
      const ar = a.querySelector('.row'), br = b.querySelector('.row');
      const aF = ar.dataset.cat === 'folder', bF = br.dataset.cat === 'folder';
      if (aF !== bF) return aF ? -1 : 1;
      let av = ar.dataset[key], bv = br.dataset[key];
      if (key === 'name') return av.localeCompare(bv, undefined, { numeric: true, sensitivity: 'base' });
      return (+bv) - (+av);
    });
    const parentLi = filelist.querySelector('li > .row.parent')?.parentElement;
    sorted.forEach(li => filelist.appendChild(li));
    if (parentLi) filelist.insertBefore(parentLi, filelist.firstChild);
  });
})();
</script>
</body>
</html>
"""


# Pre-rendered SVG icons (mirror of PHP renderIcon)
ICON_PATHS = {
    "folder":  '<path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/>',
    "image":   '<rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/>',
    "video":   '<path d="m22 8-6 4 6 4V8Z"/><rect width="14" height="12" x="2" y="6" rx="2" ry="2"/>',
    "audio":   '<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',
    "archive": '<rect width="20" height="5" x="2" y="3" rx="1"/><path d="M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8"/><path d="M10 12h4"/>',
    "code":    '<polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/>',
    "doc":     '<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><line x1="10" y1="9" x2="8" y2="9"/>',
    "sheet":   '<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/><path d="M8 13h8M8 17h8M8 9h2"/>',
    "slides":  '<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/><rect x="8" y="12" width="8" height="6" rx="1"/>',
    "file":    '<path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z"/><polyline points="14 2 14 8 20 8"/>',
}


def render_icon(cat: str) -> str:
    body = ICON_PATHS.get(cat, ICON_PATHS["file"])
    return f'<svg class="icon icon-{cat}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">{body}</svg>'

# Product folder icons keyed by directory name. When a folder's name matches
# one of these keys, we render the brand mark instead of the generic folder
# icon. Each value is (viewBox, inner SVG content).
PRODUCT_ICONS = {
    "340BCheck": ("0 0 178 195", '<path d="M160.39 46.41L88.55 100.38L30.03 56.9L88.55 19.93L116.92 38.3L89.3 61.95L77.98 51.92L77.52 51.87L53.17 51.88L89.77 80.96L144.96 36.95L88.72 0.11L88.55 0L0.39 56.17L0 56.41L88.38 120.63L88.55 120.75L175.8 56.34L160.39 46.41Z" fill="currentColor"/><path d="M161.94 83.6701L161.77 83.5601L88.55 137.64L15.28 83.8601L0.39 93.4301L0 93.6701L88.38 157.9L88.55 158.02L176.72 93.7401L177.1 93.4801L161.94 83.6701Z" fill="currentColor"/><path d="M161.94 119.86L161.77 119.75L88.55 173.83L15.28 120.05L0.39 129.62L0 129.86L88.38 194.08L88.55 194.2L176.72 129.93L177.1 129.67L161.94 119.86Z" fill="currentColor"/>'),
    "ControlCheck": ("0 0 122 121", '<path fill-rule="evenodd" clip-rule="evenodd" d="M11 25.4199V84.1599C13.6667 89.2399 18.4333 95.0033 25.3 101.45C30.08 105.962 35.202 110.098 40.62 113.82C37.7418 116.115 34.7116 118.214 31.55 120.1C24.7703 115.665 18.5021 110.494 12.86 104.68C6.66667 98.3933 2.38 92.7766 0 87.8299V30.0699C3.57849 28.3191 7.25072 26.7667 11 25.4199Z" fill="currentColor"/><path fill-rule="evenodd" clip-rule="evenodd" d="M30.56 10.52V74.94C33.6867 80.52 39.3334 86.8534 47.5 93.94C53.2215 98.9521 59.3157 103.522 65.73 107.61C62.4843 109.983 59.0908 112.148 55.57 114.09C47.6219 109.278 40.2216 103.615 33.5 97.2C26.1667 90.3 21.0934 84.1367 18.28 78.71V15.37C22.5334 13.4634 26.6267 11.8467 30.56 10.52Z" fill="currentColor"/><path fill-rule="evenodd" clip-rule="evenodd" d="M38.76 70.27C42.32 76.18 48.64 82.88 57.55 90.27C65.3793 96.8898 73.871 102.684 82.89 107.56C91.4917 103.359 99.4625 97.9729 106.57 91.56C112.129 86.7131 117.061 81.1903 121.25 75.12V51.31L110.92 62.07V71.29C106.63 76.37 103.12 79.02 98.5 82.75C93.6681 86.6203 88.4427 89.9721 82.91 92.75C77.38 89.51 72.05 86.57 66.91 82.25C61.2329 77.4179 55.9834 72.1049 51.22 66.37V14.8C63.66 12.8 74.22 12.5 82.98 13.89C91.51 15.24 100.88 19.44 111.6 24.67V27.26L83.05 56.59L75.39 47.52L57.81 45.94L83.05 75.05L121.33 34.31V16.93C107.31 8.66001 94.67 3.36001 83 1.26001C78.0175 0.391912 72.9675 -0.0297613 67.91 7.59668e-06C58.105 0.117945 48.3376 1.23709 38.76 3.34001V70.27Z" fill="currentColor"/>'),
    "CostCheck": ("0 0 106 113", '<path fill-rule="evenodd" clip-rule="evenodd" d="M54.62 65.3299C33.47 65.3299 20.62 59.5599 13.62 54.7199C5 48.7399 0 40.7099 0 32.6699C0 24.9199 5 16.7699 13.36 10.8699C20.38 5.9099 33.24 -0.000103328 54.62 -0.000103328C67.5664 -0.104458 80.2439 3.69392 91 10.8999L91.82 11.4499L51.67 49.7799L29.35 26.7799L45.89 27.9999L51.72 34.1899L72.16 14.9999C66.4637 13.2845 60.5664 12.3263 54.62 12.1499C25.62 12.1499 12.16 24.4099 12.16 32.6999C12.16 37.4599 16.26 42.5699 23.16 46.3799C31.16 50.8099 42.33 53.2499 54.66 53.2499C63.4901 53.1176 72.1917 51.1135 80.19 47.3699C88.63 43.2299 93.3 37.9299 93.3 32.3999C93.1455 30.1554 92.3197 28.0092 90.93 26.2399L90.55 25.6999L99 16.9999L99.56 17.6699C103.244 21.8071 105.316 27.1311 105.4 32.6699C105.4 39.3799 102.33 49.0599 87.71 57.0099C77.4998 62.3783 66.1551 65.2308 54.62 65.3299Z" fill="currentColor"/><path d="M103.5 53.0798L102.77 54.7798C97.67 66.6998 77 75.4598 52.77 75.4598C28.54 75.4598 7.86002 66.6998 2.76002 54.7798L2.00002 53.0798L1.28002 54.7798C0.432491 56.7438 -0.00315403 58.8608 1.71894e-05 60.9998C1.71894e-05 76.5198 23.68 88.8498 52.77 88.8498C81.86 88.8498 105.53 76.5198 105.53 60.9998C105.524 58.8587 105.078 56.7416 104.22 54.7798L103.5 53.0798Z" fill="currentColor"/><path d="M103.5 76.6099L104.22 78.2999C105.077 80.262 105.523 82.3788 105.53 84.5199C105.53 100.05 81.85 112.38 52.77 112.38C23.69 112.38 0 100.05 0 84.5199C0.00742938 82.3788 0.453255 80.262 1.31 78.2999L2 76.6099L2.73 78.2999C7.81 90.1099 28.16 98.7999 52 98.9999H53.45C77.09 98.8199 97.27 90.2999 102.57 78.6799L102.73 78.3199L103.5 76.6099Z" fill="currentColor"/>'),
    "KitCheck": ("0 0 122 99", '<path fill-rule="evenodd" clip-rule="evenodd" d="M19.54 6.30005L31.21 8.43005V98.66H19.54V6.30005Z" fill="currentColor"/><path fill-rule="evenodd" clip-rule="evenodd" d="M0 12.6101L11.66 14.7401V98.6601H0V12.6101Z" fill="currentColor"/><path fill-rule="evenodd" clip-rule="evenodd" d="M38.77 98.66H121.67V54.31L110.72 66.06V86.56L51.34 85.91V14.83L112.05 24.64V32.09L86.51 59.1L79.49 50.78L63.32 49.31L86.51 76.03L121.67 38.6V14.46L38.77 0V98.66Z" fill="currentColor"/>'),
    "Prism": ("0 0 110 90", '<path d="M21.9 26.16L12.71 11.34L76.94 11.22" fill="currentColor"/><path d="M64.01 64.3299L54.79 79.3599L21.9 26.1599" fill="currentColor"/><path d="M76.94 11.22L96.85 11.2L64.01 64.33" fill="currentColor"/><path d="M67.59 49.6499L64.01 64.3299L32.95 36.1799" fill="currentColor"/><path d="M60.87 15.56L76.94 11.22L67.59 49.65" fill="currentColor"/><path d="M32.95 36.1801L21.9 26.1601L60.87 15.5601" fill="currentColor"/>'),
    "PrivacyPro": ("0 0 131 117", '<path d="M12.5 62.5C12.8 62.6 13.1 62.5999 13.4 62.5999C15.3 62.5999 16.9 61.3 17.4 59.4C17.6 58.4 23.4 33.7999 50.4 33.7999C55.7 33.7999 60.2 34.7 64 36.2C65.5 33.8 67.3 31.6 69.3 29.7C64.1 27.2 57.9 25.7 50.3 25.7C16.6 25.7 9.4 57.4 9.3 57.7C9 59.9 10.4 62.1 12.5 62.5Z" fill="currentColor"/><path d="M23.6 26.5C24.3 26.5 25 26.3 25.7 25.9C40.7 17 56.1 16.6 72.7 24.8C74.7 25.8 77.1 25 78.1 22.9C79.1 20.9 78.3 18.5 76.2 17.5C57.2 8.19997 38.8 8.59997 21.5 18.9C19.6 20 18.9 22.5 20.1 24.5C20.9 25.8 22.2 26.5 23.6 26.5Z" fill="currentColor"/><path d="M15.7 72.4C15.9 70.2 14.3 68.2 12 68C9.80001 67.8 7.80001 69.4 7.60001 71.7C7.50001 72.8 6.70001 82.6 11.1 89.3C11.9 90.5 13.2 91.1 14.5 91.1C15.3 91.1 16 90.9 16.7 90.4C18.6 89.2 19.1 86.7 17.9 84.8C15.5 81.2 15.5 74.6 15.7 72.4Z" fill="currentColor"/><path d="M79.5 79.8999C79 85.1999 77.4 90.6999 74.6 96.0999C73.6 98.0999 74.4 100.5 76.4 101.6C77 101.9 77.6 102 78.2 102C79.7 102 81.1 101.2 81.8 99.7999C84.9 93.7999 86.7 87.5999 87.4 81.5999C84.7 81.3999 82 80.7999 79.5 79.8999Z" fill="currentColor"/><path d="M60 55.5999C58.2 54.9999 56.3 54.6999 54.2 54.5999C54.1 54.5999 54.1 54.5999 54 54.5999C40.6 54.5999 36.5 67.7999 36.2 74.7999C36.1 76.9999 37.8 78.8999 40 78.9999C42.3 79.0999 44.1 77.3999 44.2 75.0999C44.2 75.0999 44.4 71.4999 45.9 68.1999C48.2 63.1999 51.7 62.6999 54 62.6999C59.2 62.6999 62 65.9999 63.3 68.7999C66.4 75.0999 65.4 84.0999 61 89.8999C53.6 99.5999 41.6 102.9 31.1 98.0999C29.1 97.1999 26.7 98.0999 25.7 100.1C24.8 102.1 25.7 104.5 27.7 105.5C32.1 107.5 36.6 108.5 41.1 108.5C51.1 108.5 60.7 103.7 67.4 94.8999C71.2 89.8999 73.1 83.2999 73.1 76.8999C66.1 72.0999 61.1 64.3999 60 55.5999Z" fill="currentColor"/><path d="M28.7 89.4C34.5 94.4 42.6 95.2 49.5 91.5C56.4 87.7 60 80.4 58.8 72.4C58.5 70.2 56.4 68.7 54.2 69C52 69.3 50.5 71.4 50.8 73.6C51.5 78.2 49.5 82.2 45.6 84.4C41.7 86.5 37.2 86.1 34 83.3C29.9 79.7 28.7 71.6 31.3 64C34.4 54.9 41.7 49.1 50.7 48.5C53.9 48.3 56.9 48.6 59.8 49.3C60 46.6 60.6 43.9 61.5 41.4C57.9 40.5 54.1 40.1 50.2 40.4C37.8 41.1 27.8 49 23.6 61.4C19.9 72.3 22 83.6 28.7 89.4Z" fill="currentColor"/><path d="M122.7 87.3999L106.8 66.9999C110.4 62.8999 112.6 57.5999 112.6 51.6999C112.6 38.9999 102.2 28.5999 89.5 28.5999C76.8 28.5999 66.5 38.9999 66.5 51.7999C66.5 64.5999 76.9 74.8999 89.6 74.8999C93.1 74.8999 96.5 74.0999 99.5 72.6999L111.1 87.4999L122.7 87.3999ZM75.8 51.7999C75.8 44.1999 82 37.9999 89.6 37.9999C97.2 37.9999 103.4 44.1999 103.4 51.7999C103.4 59.3999 97.2 65.5999 89.6 65.5999C82 65.5999 75.8 59.3999 75.8 51.7999Z" fill="currentColor"/>'),
    "ShortageCheck": ("0 0 228 168", '<path fill-rule="evenodd" clip-rule="evenodd" d="M223.47 163.79L223.56 147.19H3.67999L3.89999 163.79H223.47Z" fill="currentColor"/><path fill-rule="evenodd" clip-rule="evenodd" d="M36.6 119.39H16.51L6.46997 135.99H36.6V119.39Z" fill="currentColor"/><path fill-rule="evenodd" clip-rule="evenodd" d="M36.6 91.4099H33.3L23.26 108.01H36.6V91.4099Z" fill="currentColor"/><path fill-rule="evenodd" clip-rule="evenodd" d="M191.85 120.22H211.94L221.97 136.82H191.85V120.22Z" fill="currentColor"/><path fill-rule="evenodd" clip-rule="evenodd" d="M191.85 92.24H195.15L205.18 108.84H191.85V92.24Z" fill="currentColor"/><path d="M164.23 78.3401V118.39H64.44V42.4401L70.52 21.4101H157.99L160.92 31.3301L115.84 79.0101L100.84 61.9901L75.6 62.0201L115.84 108.38L181.83 38.2001L171.5 3.32007H56.92L46.35 39.8801V136.48H182.32V59.1901L164.23 78.3401Z" fill="currentColor"/>'),
}


def render_product_icon(name: str) -> str:
    """If the directory name has a registered product icon, return its <svg>;
    otherwise return empty string. preserveAspectRatio centers the artwork
    inside the icon's square bounding box."""
    entry = PRODUCT_ICONS.get(name)
    if not entry:
        return ""
    viewbox, inner = entry
    return (
        f'<svg class="icon icon-product" viewBox="{viewbox}" '
        f'preserveAspectRatio="xMidYMid meet" fill="none">{inner}</svg>'
    )




# ---------- Main build ----------
def collect_entries(dir_path: Path):
    """Return entries in this directory (excluding hidden/excluded/readme)."""
    entries = []
    for child in sorted(dir_path.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower())):
        name = child.name
        if is_excluded(name):
            continue
        is_dir = child.is_dir()
        try:
            stat = child.stat()
            mtime = stat.st_mtime
            size = None if is_dir else stat.st_size
        except OSError:
            mtime, size = 0, None
        ext = "" if is_dir else child.suffix.lstrip(".").lower()
        entries.append({
            "name": name,
            "is_dir": is_dir,
            "size": size,
            "mtime": mtime,
            "ext": ext,
        })
    return entries


def build_crumbs(rel: str, depth_to_root: str) -> str:
    """rel: posix path relative to root, '' for root.
    depth_to_root: '' for root, '../' * depth for subdirs."""
    parts = [("Home", depth_to_root or "./")]
    if rel:
        accum_segments = []
        for seg in rel.split("/"):
            accum_segments.append(seg)
            # build href: from current dir, go up depth, then down into accum_segments
            up = depth_to_root or ""
            href = up + "/".join(accum_segments) + "/"
            parts.append((seg, href))
    out = []
    for i, (label, href) in enumerate(parts):
        if i > 0:
            out.append('<span class="sep">/</span>')
        out.append(f'<a href="{html.escape(href)}">{html.escape(label)}</a>')
    return "".join(out)


def build_index_for_dir(repo_root: Path, dir_path: Path):
    """Generate index.html for this directory. Returns True if written."""
    rel = dir_path.relative_to(repo_root).as_posix()
    if rel == ".":
        rel = ""

    entries = collect_entries(dir_path)
    depth = 0 if rel == "" else rel.count("/") + 1
    depth_to_root = "../" * depth if depth else ""

    # Detect notes.md (case-insensitive) — rendered into the sidebar.
    # Variable kept named readme_html for template-placeholder compatibility.
    readme_html = ""
    for entry_name in os.listdir(dir_path):
        if entry_name.lower() == "notes.md" and (dir_path / entry_name).is_file():
            try:
                content = (dir_path / entry_name).read_text(encoding="utf-8", errors="ignore")
                if content.strip():
                    rendered = render_markdown(content, "")  # links resolve relative to this dir
                    readme_html = f'<li class="readme-row"><div class="readme">{rendered}</div></li>'
            except Exception:
                pass
            break

    # Detect default file (auto-load in iframe).
    # DEFAULT_FILES intentionally bypasses is_excluded — PROTOTYPE_FILENAME is
    # in EXCLUDE_NAMES (to hide it from listings/search) but should still load.
    initial_view_name = ""
    for cand in DEFAULT_FILES:
        cand_path = dir_path / cand
        cand_ext = cand.rsplit(".", 1)[-1].lower() if "." in cand else ""
        if cand_path.is_file() and cand_ext in IFRAME_EXTS:
            initial_view_name = cand
            break

    # Build entry rows
    rows = []
    for e in entries:
        cat = file_category(e["ext"], e["is_dir"])
        # href: folders go to subdir/; files are direct file links
        if e["is_dir"]:
            href = f'{html.escape(e["name"])}/'
        else:
            href = html.escape(e["name"])
        iframable = (not e["is_dir"]) and e["ext"] in IFRAME_EXTS
        is_active = (initial_view_name and e["name"] == initial_view_name)

        date_str = datetime.fromtimestamp(e["mtime"]).strftime(DATE_FORMAT) if e["mtime"] else ""
        if e["is_dir"]:
            meta = date_str
        else:
            size_part = fmt_size(e["size"])
            meta = f"{size_part} · {date_str}".strip(" ·") if date_str else size_part

        attrs = [
            f'href="{href}"',
            f'data-name="{html.escape(e["name"], quote=True)}"',
            f'data-size="{e["size"] or 0}"',
            f'data-mtime="{int(e["mtime"])}"',
            f'data-cat="{cat}"',
        ]
        if iframable:
            # absolute href from current page (just the filename for files in this dir)
            attrs.append('data-iframe="1"')
            attrs.append(f'data-abs-href="{href}"')

        active_cls = " active" if is_active else ""
        icon_html = render_product_icon(e["name"]) if e["is_dir"] else ""
        if not icon_html:
            icon_html = render_icon(cat)
        rows.append(
            f'<li><a class="row{active_cls}" {" ".join(attrs)}>'
            f'{icon_html}'
            f'<div class="info"><div class="name">{html.escape(e["name"])}</div>'
            f'<div class="meta">{html.escape(meta)}</div></div></a></li>'
        )

    # Parent row (only if we're in a subfolder)
    parent_row = ""
    if rel:
        parent_row = (
            '<li><a class="row parent" href="../">'
            '<svg class="icon icon-up" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m12 19-7-7 7-7"/><path d="M19 12H5"/></svg>'
            '<div class="info"><div class="name">Back</div></div>'
            '</a></li>'
        )

    empty_note = '<li class="empty-list">This folder is empty.</li>' if (not entries and not rel) else ""

    # Initial state
    is_html_view = initial_view_name and initial_view_name.lower().endswith((".html", ".htm"))
    initial_lock = "" if is_html_view else "locked-open"
    viewer_active = "true" if initial_view_name else "false"
    frame_src = html.escape(initial_view_name) if initial_view_name else ""

    display_path = "/" + rel
    crumbs_html = build_crumbs(rel, depth_to_root)
    search_index_path = depth_to_root + "_search-index.json"
    site_base = depth_to_root or "./"

    output = HTML_TEMPLATE
    replacements = {
        "__TITLE__": html.escape(TITLE),
        "__DISPLAY_PATH__": html.escape(display_path),
        "__INITIAL_LOCK__": initial_lock,
        "__CRUMBS__": crumbs_html,
        "__README_BLOCK__": readme_html,
        "__PARENT_ROW__": parent_row,
        "__ENTRY_ROWS__": "\n".join(rows),
        "__EMPTY_NOTE__": empty_note,
        "__VIEWER_ACTIVE__": viewer_active,
        "__FRAME_SRC__": frame_src,
        "__SEARCH_INDEX_PATH__": search_index_path,
        "__SITE_BASE__": site_base,
    }
    for k, v in replacements.items():
        output = output.replace(k, v)

    # Marker so we know we wrote this. Placed at the top so stale-file
    # detection can find it cheaply on the next build.
    output = output.replace(
        "<!DOCTYPE html>", f"<!DOCTYPE html>\n{BUILD_MARKER}", 1
    )

    out_path = dir_path / "index.html"
    out_path.write_text(output, encoding="utf-8")
    return True


def build_search_index(repo_root: Path) -> int:
    """Walk the entire tree and emit _search-index.json. Returns the entry count."""
    items = []
    for dirpath, dirnames, filenames in os.walk(repo_root):
        # Filter dirs in place to skip excluded ones (also prunes traversal)
        dirnames[:] = [d for d in dirnames if not is_excluded(d)]
        d = Path(dirpath)
        rel_dir = d.relative_to(repo_root).as_posix()
        if rel_dir == ".":
            rel_dir = ""

        # Add directories
        for name in dirnames:
            full = (d / name)
            rel = (rel_dir + "/" + name) if rel_dir else name
            items.append({
                "name": name,
                "path": rel,
                "parent": rel_dir,
                "isDir": True,
                "iframable": False,
                "cat": "folder",
            })

        # Add files
        for name in filenames:
            if is_excluded(name):
                continue
            ext = name.rsplit(".", 1)[-1].lower() if "." in name else ""
            rel = (rel_dir + "/" + name) if rel_dir else name
            items.append({
                "name": name,
                "path": rel,
                "parent": rel_dir,
                "isDir": False,
                "iframable": ext in IFRAME_EXTS,
                "cat": file_category(ext, False),
            })

    out_path = repo_root / "_search-index.json"
    out_path.write_text(json.dumps(items, separators=(",", ":")), encoding="utf-8")
    return len(items)


def copy_source_to_output(src_root: Path, out_root: Path) -> list[str]:
    """Copy src_root to out_root, skipping excluded names. Returns a list of
    relative paths to stale generated files (committed `index.html` files
    containing BUILD_MARKER) that were skipped — for printing as warnings.

    A previous in-place build may have committed generated index.html files
    into the repo; those should NOT be treated as real prototypes. We detect
    them by content marker and exclude them from the copy.
    """
    if out_root.exists():
        shutil.rmtree(out_root)

    stale: list[str] = []

    def ignore(dir_str: str, names: list[str]) -> set[str]:
        skip: set[str] = set()
        d = Path(dir_str)
        for name in names:
            # Dotfiles (.git, .DS_Store, .gitignore, .nojekyll, ...)
            if any(name.startswith(p) for p in EXCLUDE_PREFIXES):
                skip.add(name)
                continue
            # Build artifacts and config we never copy into the output
            if name in COPY_SKIP_NAMES:
                skip.add(name)
                continue
            # Detect stale generated index.html in source: copied by previous
            # in-place builds; do not treat as a real prototype.
            # Read window is 64KB — older builds placed the marker near
            # </head>, which can sit ~10KB into the file due to embedded CSS.
            if name == "index.html":
                p = d / name
                try:
                    if p.is_file():
                        head = p.read_text(encoding="utf-8", errors="ignore")[:65536]
                        if BUILD_MARKER in head:
                            try:
                                rel = p.relative_to(src_root).as_posix()
                            except ValueError:
                                rel = str(p)
                            stale.append(rel)
                            skip.add(name)
                except OSError:
                    pass
        return skip

    shutil.copytree(src_root, out_root, ignore=ignore, dirs_exist_ok=False)
    return stale


def find_user_landings(out_root: Path) -> list[Path]:
    """Walk out_root and return absolute paths to every directory containing a
    user-provided `index.html` (a bare landing page). Stale generated
    listings were already filtered out during the copy, so any `index.html`
    present here is a real user file. Also enforces the rule that a folder
    cannot contain both `index.html` and LANDING_FILENAME — those represent
    contradictory intents (bare vs. wrapped) and indicate an authoring error.
    """
    bare_dirs: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(out_root):
        if "index.html" not in filenames:
            continue
        d = Path(dirpath)
        if LANDING_FILENAME in filenames:
            rel = d.relative_to(out_root).as_posix() or "/"
            print(
                f"Error: {rel} contains both index.html (bare landing) and "
                f"{LANDING_FILENAME} (wrapped landing). These are "
                f"contradictory — keep one and delete the other.",
                file=sys.stderr,
            )
            sys.exit(1)
        bare_dirs.append(d)
    return bare_dirs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Source root (default: current dir)")
    args = parser.parse_args()

    src_root = Path(args.root).resolve()
    if not src_root.is_dir():
        print(f"Error: {src_root} is not a directory", file=sys.stderr)
        sys.exit(1)

    out_root = src_root / OUTPUT_DIR

    print(f"Source: {src_root}")
    print(f"Output: {out_root}")
    print()

    # Pass 1: copy source -> _site, skipping excluded + stale generated files
    stale = copy_source_to_output(src_root, out_root)
    if stale:
        print("Warning: skipped stale generated files in source (left over from")
        print("a previous in-place build). Please delete these from the repo:")
        for p in stale:
            print(f"  - {p}")
        print()

    # Pass 2: identify folders the user wants served as bare landing pages
    # (a user index.html lives there; no sidebar wraps it). The build will
    # not overwrite these.
    bare_dirs = find_user_landings(out_root)
    bare_set = {d.resolve() for d in bare_dirs}

    # Pass 3: generate index.html listings for every directory EXCEPT those
    # the user has claimed for a bare landing.
    written = 0
    skipped_bare = 0
    for dirpath, dirnames, _ in os.walk(out_root):
        dirnames[:] = [d for d in dirnames if not is_excluded(d)]
        d = Path(dirpath)
        rel = d.relative_to(out_root).as_posix()
        if rel == ".":
            rel = ""
        if d.resolve() in bare_set:
            print(f"  {rel or '/'}  (bare landing — skipping listing generation)")
            skipped_bare += 1
            continue
        print(f"  {rel or '/'}")
        if build_index_for_dir(out_root, d):
            written += 1

    # Generate search index at the root of _site
    count = build_search_index(out_root)
    print()
    print(f"Wrote {written} index.html listings")
    if skipped_bare:
        print(
            f"Left {skipped_bare} user index.html file(s) in place as bare "
            f"landing page(s). To wrap one in the sidebar instead, rename it "
            f"to {LANDING_FILENAME}."
        )
    print(f"Search index: {count} entries -> {OUTPUT_DIR}/_search-index.json")

    # .nojekyll so GH Pages doesn't filter _search-index.json
    nojekyll = out_root / ".nojekyll"
    if not nojekyll.exists():
        nojekyll.write_text("", encoding="utf-8")
        print(f"Created {OUTPUT_DIR}/.nojekyll (prevents Jekyll filtering)")

    # robots.txt: block crawlers by default. If the user provides their own
    # robots.txt in source it'll have been copied to _site/ already and we
    # leave it alone.
    robots = out_root / "robots.txt"
    if not robots.exists():
        robots.write_text("User-agent: *\nDisallow: /\n", encoding="utf-8")
        print(f"Created {OUTPUT_DIR}/robots.txt (blocks all crawlers)")


if __name__ == "__main__":
    main()
